export default {
  A: [
    { code: 'A01', name: '松山區' },
    { code: 'A17', name: '信義區' },
    { code: 'A02', name: '大安區' },
    { code: 'A10', name: '中山區' },
    { code: 'A03', name: '中正區' },
    { code: 'A09', name: '大同區' },
    { code: 'A05', name: '萬華區' },
    { code: 'A11', name: '文山區' },
    { code: 'A13', name: '南港區' },
    { code: 'A14', name: '內湖區' },
    { code: 'A15', name: '士林區' },
    { code: 'A16', name: '北投區' }
  ],
  B: [
    { code: 'B01', name: '中區' },
    { code: 'B02', name: '東區' },
    { code: 'B03', name: '南區' },
    { code: 'B04', name: '西區' },
    { code: 'B05', name: '北區' },
    { code: 'B06', name: '西屯區' },
    { code: 'B07', name: '南屯區' },
    { code: 'B08', name: '北屯區' },
    { code: 'B09', name: '豐原區' },
    { code: 'B10', name: '東勢區' },
    { code: 'B11', name: '大甲區' },
    { code: 'B12', name: '清水區' },
    { code: 'B13', name: '沙鹿區' },
    { code: 'B14', name: '梧棲區' },
    { code: 'B15', name: '后里區' },
    { code: 'B16', name: '神岡區' },
    { code: 'B17', name: '潭子區' },
    { code: 'B18', name: '大雅區' },
    { code: 'B19', name: '新社區' },
    { code: 'B20', name: '石岡區' },
    { code: 'B21', name: '外埔區' },
    { code: 'B22', name: '大安區' },
    { code: 'B23', name: '烏日區' },
    { code: 'B24', name: '大肚區' },
    { code: 'B25', name: '龍井區' },
    { code: 'B26', name: '霧峰區' },
    { code: 'B27', name: '太平區' },
    { code: 'B28', name: '大里區' },
    { code: 'B29', name: '和平區' }
  ],
  C: [
    { code: 'C01', name: '中正區' },
    { code: 'C02', name: '七堵區' },
    { code: 'C03', name: '暖暖區' },
    { code: 'C04', name: '仁愛區' },
    { code: 'C05', name: '中山區' },
    { code: 'C06', name: '安樂區' },
    { code: 'C07', name: '信義區' }
  ],
  D: [
    { code: 'D09', name: '新營區' },
    { code: 'D10', name: '鹽水區' },
    { code: 'D12', name: '白河區' },
    { code: 'D11', name: '柳營區' },
    { code: 'D13', name: '後壁區' },
    { code: 'D14', name: '東山區' },
    { code: 'D15', name: '麻豆區' },
    { code: 'D16', name: '下營區' },
    { code: 'D17', name: '六甲區' },
    { code: 'D18', name: '官田區' },
    { code: 'D19', name: '大內區' },
    { code: 'D20', name: '佳里區' },
    { code: 'D25', name: '學甲區' },
    { code: 'D21', name: '西港區' },
    { code: 'D22', name: '七股區' },
    { code: 'D23', name: '將軍區' },
    { code: 'D24', name: '北門區' },
    { code: 'D26', name: '新化區' },
    { code: 'D27', name: '善化區' },
    { code: 'D28', name: '新市區' },
    { code: 'D29', name: '安定區' },
    { code: 'D30', name: '山上區' },
    { code: 'D36', name: '玉井區' },
    { code: 'D37', name: '楠西區' },
    { code: 'D38', name: '南化區' },
    { code: 'D31', name: '左鎮區' },
    { code: 'D32', name: '仁德區' },
    { code: 'D33', name: '歸仁區' },
    { code: 'D34', name: '關廟區' },
    { code: 'D35', name: '龍崎區' },
    { code: 'D39', name: '永康區' },
    { code: 'D01', name: '東區' },
    { code: 'D02', name: '南區' },
    { code: 'D04', name: '北區' },
    { code: 'D06', name: '安南區' },
    { code: 'D07', name: '安平區' },
    { code: 'D08', name: '中西區' }
  ],
  E: [
    { code: 'E01', name: '鹽埕區' },
    { code: 'E02', name: '鼓山區' },
    { code: 'E03', name: '左營區' },
    { code: 'E04', name: '楠梓區' },
    { code: 'E05', name: '三民區' },
    { code: 'E06', name: '新興區' },
    { code: 'E07', name: '前金區' },
    { code: 'E08', name: '苓雅區' },
    { code: 'E09', name: '前鎮區' },
    { code: 'E10', name: '旗津區' },
    { code: 'E11', name: '小港區' },
    { code: 'E12', name: '鳳山區' },
    { code: 'E13', name: '林園區' },
    { code: 'E14', name: '大寮區' },
    { code: 'E15', name: '大樹區' },
    { code: 'E16', name: '大社區' },
    { code: 'E17', name: '仁武區' },
    { code: 'E18', name: '鳥松區' },
    { code: 'E19', name: '岡山區' },
    { code: 'E20', name: '橋頭區' },
    { code: 'E21', name: '燕巢區' },
    { code: 'E22', name: '田寮區' },
    { code: 'E23', name: '阿蓮區' },
    { code: 'E24', name: '路竹區' },
    { code: 'E25', name: '湖內區' },
    { code: 'E26', name: '茄萣區' },
    { code: 'E27', name: '永安區' },
    { code: 'E28', name: '彌陀區' },
    { code: 'E29', name: '梓官區' },
    { code: 'E30', name: '旗山區' },
    { code: 'E31', name: '美濃區' },
    { code: 'E32', name: '六龜區' },
    { code: 'E33', name: '甲仙區' },
    { code: 'E34', name: '杉林區' },
    { code: 'E35', name: '內門區' },
    { code: 'E36', name: '茂林區' },
    { code: 'E37', name: '桃源區' },
    { code: 'E38', name: '那瑪夏區' }
  ],
  F: [
    { code: 'F14', name: '板橋區' },
    { code: 'F05', name: '三重區' },
    { code: 'F18', name: '中和區' },
    { code: 'F33', name: '永和區' },
    { code: 'F01', name: '新莊區' },
    { code: 'F07', name: '新店區' },
    { code: 'F17', name: '樹林區' },
    { code: 'F16', name: '鶯歌區' },
    { code: 'F15', name: '三峽區' },
    { code: 'F27', name: '淡水區' },
    { code: 'F28', name: '汐止區' },
    { code: 'F21', name: '瑞芳區' },
    { code: 'F19', name: '土城區' },
    { code: 'F04', name: '蘆洲區' },
    { code: 'F03', name: '五股區' },
    { code: 'F06', name: '泰山區' },
    { code: 'F02', name: '林口區' },
    { code: 'F09', name: '深坑區' },
    { code: 'F08', name: '石碇區' },
    { code: 'F10', name: '坪林區' },
    { code: 'F30', name: '三芝區' },
    { code: 'F31', name: '石門區' },
    { code: 'F32', name: '八里區' },
    { code: 'F22', name: '平溪區' },
    { code: 'F23', name: '雙溪區' },
    { code: 'F24', name: '貢寮區' },
    { code: 'F25', name: '金山區' },
    { code: 'F26', name: '萬里區' },
    { code: 'F11', name: '烏來區' }
  ],
  G: [
    { code: 'G01', name: '宜蘭市' },
    { code: 'G06', name: '羅東鎮' },
    { code: 'G09', name: '蘇澳鎮' },
    { code: 'G02', name: '頭城鎮' },
    { code: 'G03', name: '礁溪鄉' },
    { code: 'G04', name: '壯圍鄉' },
    { code: 'G05', name: '員山鄉' },
    { code: 'G08', name: '冬山鄉' },
    { code: 'G07', name: '五結鄉' },
    { code: 'G10', name: '三星鄉' },
    { code: 'G11', name: '大同鄉' },
    { code: 'G12', name: '南澳鄉' }
  ],
  H: [
    { code: 'H01', name: '桃園區' },
    { code: 'H03', name: '中壢區' },
    { code: 'H02', name: '大溪區' },
    { code: 'H04', name: '楊梅區' },
    { code: 'H05', name: '蘆竹區' },
    { code: 'H06', name: '大園區' },
    { code: 'H07', name: '龜山區' },
    { code: 'H08', name: '八德區' },
    { code: 'H09', name: '龍潭區' },
    { code: 'H10', name: '平鎮區' },
    { code: 'H11', name: '新屋區' },
    { code: 'H12', name: '觀音區' },
    { code: 'H13', name: '復興區' }
  ],
  I: [
    { code: 'I01', name: '東區' },
    { code: 'I02', name: '西區' }
  ],
  J: [
    { code: 'J05', name: '竹北市' },
    { code: 'J02', name: '竹東鎮' },
    { code: 'J04', name: '新埔鎮' },
    { code: 'J03', name: '關西鎮' },
    { code: 'J06', name: '湖口鄉' },
    { code: 'J09', name: '新豐鄉' },
    { code: 'J10', name: '芎林鄉' },
    { code: 'J08', name: '橫山鄉' },
    { code: 'J12', name: '北埔鄉' },
    { code: 'J11', name: '寶山鄉' },
    { code: 'J13', name: '峨眉鄉' },
    { code: 'J14', name: '尖石鄉' },
    { code: 'J15', name: '五峰鄉' }
  ],
  K: [
    { code: 'K01', name: '苗栗市' },
    { code: 'K02', name: '苑裡鎮' },
    { code: 'K03', name: '通霄鎮' },
    { code: 'K09', name: '竹南鎮' },
    { code: 'K10', name: '頭份市' },
    { code: 'K12', name: '後龍鎮' },
    { code: 'K16', name: '卓蘭鎮' },
    { code: 'K15', name: '大湖鄉' },
    { code: 'K04', name: '公館鄉' },
    { code: 'K05', name: '銅鑼鄉' },
    { code: 'K14', name: '南庄鄉' },
    { code: 'K08', name: '頭屋鄉' },
    { code: 'K06', name: '三義鄉' },
    { code: 'K07', name: '西湖鄉' },
    { code: 'K11', name: '造橋鄉' },
    { code: 'K13', name: '三灣鄉' },
    { code: 'K17', name: '獅潭鄉' },
    { code: 'K18', name: '泰安鄉' }
  ],
  M: [
    { code: 'M01', name: '南投市' },
    { code: 'M02', name: '埔里鎮' },
    { code: 'M03', name: '草屯鎮' },
    { code: 'M04', name: '竹山鎮' },
    { code: 'M05', name: '集集鎮' },
    { code: 'M06', name: '名間鄉' },
    { code: 'M07', name: '鹿谷鄉' },
    { code: 'M08', name: '中寮鄉' },
    { code: 'M09', name: '魚池鄉' },
    { code: 'M10', name: '國姓鄉' },
    { code: 'M11', name: '水里鄉' },
    { code: 'M12', name: '信義鄉' },
    { code: 'M13', name: '仁愛鄉' }
  ],
  N: [
    { code: 'N01', name: '彰化市' },
    { code: 'N02', name: '鹿港鎮' },
    { code: 'N03', name: '和美鎮' },
    { code: 'N09', name: '線西鄉' },
    { code: 'N10', name: '伸港鄉' },
    { code: 'N11', name: '福興鄉' },
    { code: 'N12', name: '秀水鄉' },
    { code: 'N13', name: '花壇鄉' },
    { code: 'N14', name: '芬園鄉' },
    { code: 'N05', name: '員林市' },
    { code: 'N06', name: '溪湖鎮' },
    { code: 'N07', name: '田中鎮' },
    { code: 'N15', name: '大村鄉' },
    { code: 'N16', name: '埔鹽鄉' },
    { code: 'N17', name: '埔心鄉' },
    { code: 'N18', name: '永靖鄉' },
    { code: 'N19', name: '社頭鄉' },
    { code: 'N20', name: '二水鄉' },
    { code: 'N04', name: '北斗鎮' },
    { code: 'N08', name: '二林鎮' },
    { code: 'N21', name: '田尾鄉' },
    { code: 'N22', name: '埤頭鄉' },
    { code: 'N23', name: '芳苑鄉' },
    { code: 'N24', name: '大城鄉' },
    { code: 'N25', name: '竹塘鄉' },
    { code: 'N26', name: '溪州鄉' }
  ],
  O: [
    { code: 'O01', name: '東區' },
    { code: 'O02', name: '北區' },
    { code: 'O03', name: '香山區' }
  ],
  P: [
    { code: 'P01', name: '斗六市' },
    { code: 'P02', name: '斗南鎮' },
    { code: 'P03', name: '虎尾鎮' },
    { code: 'P04', name: '西螺鎮' },
    { code: 'P05', name: '土庫鎮' },
    { code: 'P06', name: '北港鎮' },
    { code: 'P07', name: '古坑鄉' },
    { code: 'P08', name: '大埤鄉' },
    { code: 'P09', name: '莿桐鄉' },
    { code: 'P10', name: '林內鄉' },
    { code: 'P11', name: '二崙鄉' },
    { code: 'P12', name: '崙背鄉' },
    { code: 'P13', name: '麥寮鄉' },
    { code: 'P14', name: '東勢鄉' },
    { code: 'P15', name: '褒忠鄉' },
    { code: 'P16', name: '臺西鄉' },
    { code: 'P17', name: '元長鄉' },
    { code: 'P18', name: '四湖鄉' },
    { code: 'P19', name: '口湖鄉' },
    { code: 'P20', name: '水林鄉' }
  ],
  Q: [
    { code: 'Q12', name: '太保市' },
    { code: 'Q02', name: '朴子市' },
    { code: 'Q03', name: '布袋鎮' },
    { code: 'Q04', name: '大林鎮' },
    { code: 'Q05', name: '民雄鄉' },
    { code: 'Q06', name: '溪口鄉' },
    { code: 'Q07', name: '新港鄉' },
    { code: 'Q08', name: '六腳鄉' },
    { code: 'Q09', name: '東石鄉' },
    { code: 'Q10', name: '義竹鄉' },
    { code: 'Q11', name: '鹿草鄉' },
    { code: 'Q13', name: '水上鄉' },
    { code: 'Q14', name: '中埔鄉' },
    { code: 'Q15', name: '竹崎鄉' },
    { code: 'Q16', name: '梅山鄉' },
    { code: 'Q17', name: '番路鄉' },
    { code: 'Q18', name: '大埔鄉' },
    { code: 'Q20', name: '阿里山鄉' }
  ],
  T: [
    { code: 'T01', name: '屏東市' },
    { code: 'T02', name: '潮州鎮' },
    { code: 'T03', name: '東港鎮' },
    { code: 'T04', name: '恆春鎮' },
    { code: 'T05', name: '萬丹鄉' },
    { code: 'T06', name: '長治鄉' },
    { code: 'T07', name: '麟洛鄉' },
    { code: 'T08', name: '九如鄉' },
    { code: 'T09', name: '里港鄉' },
    { code: 'T10', name: '鹽埔鄉' },
    { code: 'T11', name: '高樹鄉' },
    { code: 'T12', name: '萬巒鄉' },
    { code: 'T13', name: '內埔鄉' },
    { code: 'T14', name: '竹田鄉' },
    { code: 'T15', name: '新埤鄉' },
    { code: 'T16', name: '枋寮鄉' },
    { code: 'T17', name: '新園鄉' },
    { code: 'T18', name: '崁頂鄉' },
    { code: 'T19', name: '林邊鄉' },
    { code: 'T20', name: '南州鄉' },
    { code: 'T21', name: '佳冬鄉' },
    { code: 'T22', name: '琉球鄉' },
    { code: 'T23', name: '車城鄉' },
    { code: 'T24', name: '滿州鄉' },
    { code: 'T25', name: '枋山鄉' },
    { code: 'T26', name: '三地門鄉' },
    { code: 'T27', name: '霧臺鄉' },
    { code: 'T28', name: '瑪家鄉' },
    { code: 'T29', name: '泰武鄉' },
    { code: 'T30', name: '來義鄉' },
    { code: 'T31', name: '春日鄉' },
    { code: 'T32', name: '獅子鄉' },
    { code: 'T33', name: '牡丹鄉' }
  ],
  U: [
    { code: 'U01', name: '花蓮市' },
    { code: 'U07', name: '鳳林鎮' },
    { code: 'U03', name: '玉里鎮' },
    { code: 'U04', name: '新城鄉' },
    { code: 'U05', name: '吉安鄉' },
    { code: 'U06', name: '壽豐鄉' },
    { code: 'U02', name: '光復鄉' },
    { code: 'U08', name: '豐濱鄉' },
    { code: 'U09', name: '瑞穗鄉' },
    { code: 'U10', name: '富里鄉' },
    { code: 'U11', name: '秀林鄉' },
    { code: 'U12', name: '萬榮鄉' },
    { code: 'U13', name: '卓溪鄉' }
  ],
  V: [
    { code: 'V01', name: '臺東市' },
    { code: 'V02', name: '成功鎮' },
    { code: 'V03', name: '關山鎮' },
    { code: 'V04', name: '卑南鄉' },
    { code: 'V09', name: '鹿野鄉' },
    { code: 'V10', name: '池上鄉' },
    { code: 'V07', name: '東河鄉' },
    { code: 'V08', name: '長濱鄉' },
    { code: 'V06', name: '太麻里鄉' },
    { code: 'V05', name: '大武鄉' },
    { code: 'V11', name: '綠島鄉' },
    { code: 'V13', name: '海端鄉' },
    { code: 'V12', name: '延平鄉' },
    { code: 'V15', name: '金峰鄉' },
    { code: 'V14', name: '達仁鄉' },
    { code: 'V16', name: '蘭嶼鄉' }
  ],
  W: [
    { code: 'W03', name: '金城鎮' },
    { code: 'W02', name: '金沙鎮' },
    { code: 'W01', name: '金湖鎮' },
    { code: 'W04', name: '金寧鄉' },
    { code: 'W05', name: '烈嶼鄉' },
    { code: 'W06', name: '烏坵鄉' }
  ],
  X: [
    { code: 'X01', name: '馬公市' },
    { code: 'X02', name: '湖西鄉' },
    { code: 'X03', name: '白沙鄉' },
    { code: 'X04', name: '西嶼鄉' },
    { code: 'X05', name: '望安鄉' },
    { code: 'X06', name: '七美鄉' }
  ],
  Z: [
    { code: 'Z01', name: '南竿鄉' },
    { code: 'Z02', name: '北竿鄉' },
    { code: 'Z03', name: '莒光鄉' },
    { code: 'Z04', name: '東引鄉' }
  ]
}
